apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: disk-usage-alerts
  namespace: argocd
  labels:
    app: disk-usage-alerts
spec:
  project: default
  source:
    repoURL: https://github.com/darylemb/gitops-dmxyz.git
    targetRevision: feat/disk-usage-alerts
    path: apps
    # Solo tomar este archivo específico del directorio apps/
    directory:
      include: '{disk-usage-alerts.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true