apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 80.14.4
    helm:
      values: |
        grafana:
          grafana.ini:
            security:
              allow_embedding: false
              cookie_samesite: none
          additionalDataSources:
            - name: Prometheus
              type: prometheus
              url: http://kube-prometheus-stack-prometheus.monitoring:9090
              isDefault: true
            - name: Loki
              type: loki
              url: http://loki-stack.monitoring:3100
              isDefault: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - Replace=true